[staging]
staging-server ansible_host=192.168.1.50 ansible_user=deployer ansible_python_interpreter=/usr/bin/python3

[production]
prod-server-01 ansible_host=192.168.1.100 ansible_user=deployer ansible_python_interpreter=/usr/bin/python3
prod-server-02 ansible_host=192.168.1.101 ansible_user=deployer ansible_python_interpreter=/usr/bin/python3

[localhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
app_dir=/opt/nominaflow
app_user=nominaflow
app_group=nominaflow
app_version=1.0.0
